service: pgi-serverless

frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - '!./**'
    - src/**
    - node_modules/**

functions:
  - ${file(functions.yml)}
